management:
  endpoints:
    web:
      exposure:
        include: "*"   # * 在yaml 文件属于关键字，所以需要加引号

spring:
  application:
    name: demo
hystrix:
  dashboard:
    proxy-stream-allow-list: localhost

eurekas:
  user: admin
  password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://${eurekas.user}:${eurekas.password}@localhost:8761/eureka # 指定服务注册中心

turbine:
  aggregator:
    clusterConfig：Turbine