server:
  port: 8768

spring:
  application:
    name: eureka-producer

eurekas:
  user: admin
  password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://${eurekas.user}:${eurekas.password}@localhost:8761/eureka # 指定服务注册中心
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
