server:
  port: 2001
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://c.biancheng.net
          predicates:
            - Path=/spring_cloud/**   # 支持多级 Path加两个**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
