server:
  port: 8763

spring:
  application:
    name: eureka-consumer

eurekas:
  user: admin
  password: 123456
  producername: EUREKA-PRODUCER

eureka:
  client:
    service-url:
      defaultZone: http://${eurekas.user}:${eurekas.password}@localhost:8761/eureka # 指定服务注册中心