spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webstudy?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  logging:
    level:
      root:info
  application:
    name: rabbit-mq
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /study
    port: 5672
logging:
  level:
    com.study.spring.utils.OkHttp:
     error
  config: classpath:logback-spring.xml