spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webstudy?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  logging:
    level:
      root:info